[config]

# [templates.hyprland]
# input_path = '~/.config/matugen/templates/hyprland-colors.conf'
# output_path = '~/.config/matugen-outs/hyprland-colors.conf'
# post_hook = 'hyprctl reload'

# [templates.kitty]
# input_path = '~/.config/matugen/templates/kitty-colors.conf'
# output_path = '~/.config/matugen-outs/kitty-colors.conf'
# post_hook = 'kill -SIGUSR1 $(pgrep kitty)'

# [templates.rofi]
# input_path = '~/.config/matugen/templates/rofi-colors.rasi'
# output_path = '~/.config/matugen-outs/rofi-colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = '~/.config/waybar/restart.sh'

# [templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/colors.css'
